module.exports = {
  // HRF system
  HRF_SYSTEM_UPS: "SAP_TRP_HRF_MIGR_PARAMS",
  HRF_SYSTEM_HOST_KEY: "HFR_SYSTEM_HOST",
  HRF_ENDPOINT_ALL_RULES: "sap/hrf/api/res/staticArtifacts.xsodata/Rule",
  HRF_ENDPOINT_RULE_CONTENT: "sap/hrf/service/rule",

  // CPBR system
  CPBR_SYSTEM_ACCESS_TOKEN_ADDRESS_KEY: "CPBR_SYSTEM_ACCESS_TOKEN_ADDRESS",
  CPBR_SYSTEM_ACCESS_CLIENT_ID_KEY: "CPBR_SYSTEM_ACCESS_CLIENT_ID",
  CPBR_SYSTEM_ACCESS_CLIENT_SECRET_KEY: "CPBR_SYSTEM_ACCESS_CLIENT_SECRET",
  CPBR_ENDPOINT_RULE_SERVICE_API_KEY: "CPBR_ENDPOINT_RULE_SERVICE_API",

  HTTP_RESPONSE_TYPE: "json",
  HTTP_MSG_XFRM: "application/x-www-form-urlencoded;charset=utf-8",
  HTTP_MSG_JSON: "application/json;charset=utf-8",
  HTTP_METHOD_GET: "GET",
  HTTP_METHOD_POST: "POST",
  HTTP_METHOD_PUT: "PUT"
};
